### ISSUE TITLE
Log error line numbers

### ISSUE THREAD

**Issue by saturnaliam** [aleksander-ciesielski/isaac-stats-plus#11]
Unsure if this is possible, but maybe logging the line number an error occurred on could be useful? A few people have talked about errors when restarting the game with Repentogon, and adding a line number to the error could help with narrowing down where this error occurs.
**note**: i was going to try to solve this problem but i'm not familiar enough with the project structure to even try to solve the issue, so having a line number / file included would also just help with letting other people make improvements.

**Comment by aleksander-ciesielski** [comment]
hey, thanks for trying to fix the issue! unfortunately the error handling is kinda scuffed in this project + it being transpiled from TypeScript to Lua doesn't help 😅 that's also one of the reasons there won't be an exact line of code in the error message as TSTL doesn't support sourcemaps

I finally have some time to work on this though so I'll be trying to fix it myself 😉 also closing in favor of #8 - feel free to comment there though

**Comment by saturnaliam** [comment]
yeah honestly i tried reading some of the error handling and i had no clue what was going on tbh LOL but good luck fixing it! yeah though id imagine transpiling would ruin line numbers and whatnot
