### ISSUE TITLE
The statistics are not shown. How can i fix it?

### ISSUE THREAD

**Issue by roysy** [aleksander-ciesielski/isaac-stats-plus#12]
I installed the mod in my game, disabled all other mods and it still doesn't work. how could i fix it?

**Comment by aleksander-ciesielski** [comment]
please post your log file, otherwise I can't help you. it's in the `C:\Users\USER\Documents\My games\Binding of Isaac Repentance\log.txt`

also make sure the mod is enabled and you play for like 2 mins with it enabled (even if it doesn't work) before you post the log file

**Comment by roysy** [comment]
[log.txt](https://github.com/user-attachments/files/15597740/log.txt)
this?

**Comment by aleksander-ciesielski** [comment]
yes. I don't see any errors, it should work. do you have found hud enabled in the game options? it must be enabled for the mod to work

**Comment by roysy** [comment]
That was the problem, sorry, thank you very much for the help
