### ISSUE TITLE
Crash Pressing R

### ISSUE THREAD

**Issue by geuks** [aleksander-ciesielski/isaac-stats-plus#2]
Hi i removed the folder of the old mod (Damage Multiplier Stat) and the folder of this mod,i re-installed this mod and my game still crashing sometimes when i use R for a new run.
[log.txt](https://github.com/aleksander-ciesielski/isaac-stats-plus/files/13464361/log.txt)

[INFO] - Lua stack trace:
[INFO] - [C](-1): HasCollectible
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(85): callbackFn
[INFO] - ...aac Rebirth/mods/stats-plus_2729900570/lualib_bundle.lua(304): ?
[INFO] - ...ces/extension/provider/resolvers/ComputablesResolver.lua(63): ?
[INFO] - [C](-1): pcall
[INFO] - ...ces/extension/provider/resolvers/ComputablesResolver.lua(60): getTotalCollectibleMultiplier
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(135): ?
[INFO] - [C](-1): pcall
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(133): recomputeMultiplier
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(154): Function
[INFO] - Caught exception, writing minidump...

**Comment by geuks** [comment]
I'm using this mod for restarting, https://steamcommunity.com/sharedfiles/filedetails/?id=2917382429

**Comment by geuks** [comment]
I fixed it by modifying this line in createDamageMultiplierProvider.lua:


```
getTotalCollectibleMultiplier = function(self, entityPlayer)
                local affectedCollectibles = __TS__ArrayFrom(__TS__New(
                    Set,
                    self:getAffectedCollectibles()
                ))
                return __TS__ArrayReduce(
                    affectedCollectibles,
                    function(____, acc, collectible) return (entityPlayer:HasCollectible(collectible) or entityPlayer:GetEffects():HasCollectibleEffect(collectible)) and acc * self:getCollectibleMultiplier(collectible, entityPlayer) or acc * NEUTRAL_MULTIPLIER end,
                    NEUTRAL_MULTIPLIER
                )
            end

```
by


```
getTotalCollectibleMultiplier = function(self, entityPlayer)
                local affectedCollectibles = __TS__ArrayFrom(__TS__New(
                    Set,
                    self:getAffectedCollectibles()
                ))
                return __TS__ArrayReduce(
                    affectedCollectibles,
                    function(____, acc, collectible)
                        local success, collectibleMultiplier = pcall(self.getCollectibleMultiplier, self, collectible, entityPlayer)
                        if success then
                            return (entityPlayer:HasCollectible(collectible) or entityPlayer:GetEffects():HasCollectibleEffect(collectible)) and acc * collectibleMultiplier or acc * NEUTRAL_MULTIPLIER
                        else
                            Isaac.DebugString("Error when calculating collectible multiplier : " .. collectible .. " - " .. collectibleMultiplier)
                            return acc * NEUTRAL_MULTIPLIER
                        end
                    end,
                    NEUTRAL_MULTIPLIER
                )
            end

```

**Comment by aleksander-ciesielski** [comment]
hey, thank you for reporting the issue!

I managed to reproduce it, but it required hundreds or even thousands of restarts - did you experience something similar or can it also happen within the first couple of restarts? Also it's weird that this error is happening as [this function invocation is wrapped inside `try/catch` statement](https://github.com/aleksander-ciesielski/isaac-stats-plus/blob/main/packages/stats-plus-essentials-addon/src/providers/damageMultiplierProvider/createDamageMultiplierProvider.ts#L120) which is transpiled down to Lua `pcall`, so theoretically it shouldn't throw 🤔

I analysed the memory usage as well and doesn't look like there's a memory leak.

**Comment by geuks** [comment]
I don't know if this helps, but I provided some context to chatGPT and it answered this:
![image](https://github.com/aleksander-ciesielski/isaac-stats-plus/assets/23451354/5645fcab-b6b7-4730-92c7-139240455cf9)

**Comment by aleksander-ciesielski** [comment]
I have good news: I think I found the root cause of this (and related) errors, and apparently, it was due to not unloading the damage multiplier provider after the game restart, which caused it to recompute the multiplier for a player that no longer exists. Still, it shouldn't crash the game as the recomputation was wrapped inside a `try/catch` statement, but whatever.

The fixed version has already been released and shouldn't crash anymore. If it does, though, feel free to re-open the issue; thanks 🤗
