### ISSUE TITLE
~10-20% Chance to Crash at Start When Playing as Jacob and Esau

### ISSUE THREAD

**Issue by Tutturu1362** [aleksander-ciesielski/isaac-stats-plus#3]
I was working on completion marks for Jacob and Esau when I noticed that I was crashing a lot upon starting a run with them. Went through the "rule of halfs" for troubleshooting mods after disabling my recent ones since I only started seeing this crash a few days ago and found that the game stopped crashing when starting a run as Jacob and Esau when only this mod was disabled and the rest of my mods were enabled. I tested a few other characters with this mod enabled and found no crashing on anybody aside from Jacob and Esau when starting a run. Granted, I only tested a few characters for around 15 resets each, so I don't know if some other character may have this issue as well, but I suspect that it has something to do with having to generate two multiplier stats instead of one. I tested the crashing by both starting runs from the menu and from simply holding "r" at the start of a run and found that there was around a 10-20% chance that the game would simply crash at the start of a new run. I checked the log file multiple times and it always ended the exact same:

[INFO] - Lua stack trace:
[INFO] - [C](-1): HasCollectible
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(85): callbackFn
[INFO] - ...aac Rebirth/mods/stats-plus_2729900570/lualib_bundle.lua(304): ?
[INFO] - ...ces/extension/provider/resolvers/ComputablesResolver.lua(63): ?
[INFO] - [C](-1): pcall
[INFO] - ...ces/extension/provider/resolvers/ComputablesResolver.lua(60): getTotalCollectibleMultiplier
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(135): ?
[INFO] - [C](-1): pcall
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(133): recomputeMultiplier
[INFO] - ...ageMultiplierProvider/createDamageMultiplierProvider.lua(154): Function
[INFO] - Caught exception, writing minidump...

Here is one of the log files:

[log.txt](https://github.com/aleksander-ciesielski/isaac-stats-plus/files/13482984/log.txt)

Edit: It seems to happen only if I have other mods enabled alongside this one. I tried to see if it was any one specific mod that was causing this issue, but it seems like many of them when bundled together with this one trigger the crashes. I'm unsure about what is causing this incompatibility since it looks like multiple types of mods that seemingly don't interact with this one still cause it to crash.

**Comment by aleksander-ciesielski** [comment]
hey, thank you for reporting the issue!

I don't think this is related in any way to Jacob & Esau and the same error occurs for other characters as well - see #2 (it's still unresolved so if you have anything insightful, please let me know there 🙏).
