### ISSUE TITLE
Error when dying: attempt to concatenate a table value (local 'msg')

### ISSUE THREAD

**Issue by alexlnkp** [aleksander-ciesielski/isaac-stats-plus#8]
The following error appears to occur when dying (not sure if with a specific character or not, but it happens)
The easiest way to reproduce this error is to pick tainted lost and die in a sacrifice room.

DISCLAIMER: I am playing with Repentogon, but the error appears to occur even without it. I have no other mod related to stat display or anything like that.
The error also occurs not just for me, but rather for multiple people, as it appears.

"MC_POST_RENDER" from "stats-plus" failed: resources/scripts/main_ex.lua:734: attempt to concatenate a table value (local 'msg')
Stack Traceback:
  resources/scripts/main_ex.lua:734: in function at line 733
  in method error
  ...ats-plus_2729900570/services/menu/ModCallbackService.lua:98: in function '____catch'
  ...ats-plus_2729900570/services/menu/ModCallbackService.lua:110: in function at line 90

**Comment by aleksander-ciesielski** [comment]
hey, thanks for opening the issue! this problem was already mentioned briefly in #4 but I'll close it in favor to this issue as yours is more focused on this particular problem. If I'm not mistaken, it doesn't break the mod nor crashes the game at all, right? It's just annoying for people using Repentogon as it's logged when a new run is started.

**Comment by alexlnkp** [comment]
> hey, thanks for opening the issue! this problem was already mentioned briefly in #4 but I'll close it in favor of this issue as yours is more focused on this particular problem. If I'm not mistaken, it doesn't break the mod nor crashes the game at all, right? It's just annoying for people using Repentogon as it's logged when a new run is started.

Yeah, that's the only downside to the error. However, it would be generally very nice for it to not appear with Repentogon, so I'd really appreciate if it'll be fixed

**Comment by Singulariity** [comment]
> hey, thanks for opening the issue! this problem was already mentioned briefly in #4 but I'll close it in favor of this issue as yours is more focused on this particular problem. If I'm not mistaken, it doesn't break the mod nor crashes the game at all, right? It's just annoying for people using Repentogon as it's logged when a new run is started.

The error doesn't seem to cause a problem but it seems to prevent some mods to work

**Comment by omfgnuts** [comment]
Hope this will still get fixed tho, that message stays on the screen, and is kinda annoying.

I'll provide additional logs if necessary

**Comment by aleksander-ciesielski** [comment]
hey guys, I fixed it in 2.0.7! it's already released so from now it should no longer happen. please reopen the issue if it does though 🙂
